$content = Get-Content "src\App.tsx" -Raw
$content = $content -replace "import \{ PrescriptionSignature \} from", "import PrescriptionSignature from"
$content = $content -replace "import \{ RecordDownload \} from", "import RecordDownload from"
$content = $content -replace "import \{ HealthSummary \} from", "import HealthSummary from"
$content = $content -replace "import \{ MedicationAdherence \} from", "import MedicationAdherence from"
$content = $content -replace "import \{ SymptomChecker \} from", "import SymptomChecker from"
$content = $content -replace "import \{ SecureMessaging \} from", "import SecureMessaging from"
$content = $content -replace "import \{ DoctorPerformance \} from", "import DoctorPerformance from"
$content = $content -replace "import \{ AppointmentAnalytics \} from", "import AppointmentAnalytics from"
$content = $content -replace "import \{ RevenueReports \} from", "import RevenueReports from"
$content = $content -replace "import \{ InventoryAnalytics \} from", "import InventoryAnalytics from"
$content = $content -replace "import \{ PatientDemographics \} from", "import PatientDemographics from"
$content = $content -replace "import \{ InsuranceClaims \} from", "import InsuranceClaims from"
$content = $content -replace "import \{ APIDocumentation \} from", "import APIDocumentation from"
$content = $content -replace "import \{ PatientTimeline \} from", "import PatientTimeline from"
$content = $content -replace "import \{ ProblemList \} from", "import ProblemList from"
$content = $content -replace "import \{ ImmunizationTracker \} from", "import ImmunizationTracker from"
$content = $content -replace "import \{ RecurringAppointmentForm \} from", "import RecurringAppointmentForm from"
$content = $content -replace "import \{ Waitlist \} from", "import Waitlist from"
$content = $content -replace "import \{ PaymentPlans \} from", "import PaymentPlans from"
$content = $content -replace "import \{ ReorderManagement \} from", "import ReorderManagement from"
$content = $content -replace "import \{ BatchTracking \} from", "import BatchTracking from"
Set-Content "src\App.tsx" $content -NoNewline
Write-Host "Fixed App.tsx imports"
